// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzacRCp6FMp1lY6_yC8dB64sq13KSjdN0',
    appId: '1:635658051968:web:7b61e07a8b42ae51256165',
    messagingSenderId: '635658051968',
    projectId: 'quiz-bible-44f41',
    authDomain: 'quiz-bible-44f41.firebaseapp.com',
    storageBucket: 'quiz-bible-44f41.appspot.com',
    measurementId: 'G-C8TE4JRT4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVko6hwucDs4tRTZ_fL_LfcpRELp3TcFM',
    appId: '1:635658051968:android:a17e9dd6333a3ac9256165',
    messagingSenderId: '635658051968',
    projectId: 'quiz-bible-44f41',
    storageBucket: 'quiz-bible-44f41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnWevd0FPPFLm5MArxw0wERJi4umcHu60',
    appId: '1:635658051968:ios:7eb18cb6ae2a88eb256165',
    messagingSenderId: '635658051968',
    projectId: 'quiz-bible-44f41',
    storageBucket: 'quiz-bible-44f41.appspot.com',
    androidClientId: '635658051968-pm7m6md7q1sgo0vibb8te814issr8ka1.apps.googleusercontent.com',
    iosClientId: '635658051968-14jhe8skp5dslo3atd785s6o5imis6s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gypse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnWevd0FPPFLm5MArxw0wERJi4umcHu60',
    appId: '1:635658051968:ios:7eb18cb6ae2a88eb256165',
    messagingSenderId: '635658051968',
    projectId: 'quiz-bible-44f41',
    storageBucket: 'quiz-bible-44f41.appspot.com',
    androidClientId: '635658051968-pm7m6md7q1sgo0vibb8te814issr8ka1.apps.googleusercontent.com',
    iosClientId: '635658051968-14jhe8skp5dslo3atd785s6o5imis6s1.apps.googleusercontent.com',
    iosBundleId: 'com.example.gypse',
  );
}
