import 'package:gypse/common/utils/enums/books_enum.dart';
import 'package:gypse/game/presentation/models/ui_answer.dart';
import 'package:gypse/game/presentation/models/ui_question.dart';

List<UiQuestion> questionsMock = [
  const UiQuestion(
    'Mock2',
    text: 'What is the largest planet in our solar system?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock2',
        isRightAnswer: true,
        text: 'Jupiter',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock2',
        isRightAnswer: false,
        text: 'Saturn',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock2',
        isRightAnswer: false,
        text: 'Mars',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock2',
        isRightAnswer: false,
        text: 'Earth',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
  const UiQuestion(
    'Mock3',
    text: 'Who painted the Mona Lisa?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock3',
        isRightAnswer: true,
        text: 'Leonardo da Vinci',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock3',
        isRightAnswer: false,
        text: 'Pablo Picasso',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock3',
        isRightAnswer: false,
        text: 'Vincent van Gogh',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock3',
        isRightAnswer: false,
        text: 'Michelangelo',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
  const UiQuestion(
    'Mock4',
    text: 'What is the chemical symbol for gold?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock4',
        isRightAnswer: true,
        text: 'Au',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock4',
        isRightAnswer: false,
        text: 'Ag',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock4',
        isRightAnswer: false,
        text: 'Fe',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock4',
        isRightAnswer: false,
        text: 'Cu',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
  const UiQuestion(
    'Mock5',
    text: 'What is the tallest mountain in the world?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock5',
        isRightAnswer: true,
        text: 'Mount Everest',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock5',
        isRightAnswer: false,
        text: 'K2',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock5',
        isRightAnswer: false,
        text: 'Makalu',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock5',
        isRightAnswer: false,
        text: 'Kangchenjunga',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
  const UiQuestion(
    'Mock6',
    text: 'What is the largest ocean in the world?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock6',
        isRightAnswer: true,
        text: 'Pacific Ocean',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock6',
        isRightAnswer: false,
        text: 'Atlantic Ocean',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock6',
        isRightAnswer: false,
        text: 'Indian Ocean',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock6',
        isRightAnswer: false,
        text: 'Arctic Ocean',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
  const UiQuestion(
    'Mock7',
    text: 'What is the largest animal in the world?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock7',
        isRightAnswer: true,
        text: 'Blue Whale',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock7',
        isRightAnswer: false,
        text: 'Elephant',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock7',
        isRightAnswer: false,
        text: 'Giraffe',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock7',
        isRightAnswer: false,
        text: 'Hippopotamus',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
  const UiQuestion(
    'Mock8',
    text: 'What is the largest country in the world?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock8',
        isRightAnswer: true,
        text: 'Russia',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock8',
        isRightAnswer: false,
        text: 'Canada',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock8',
        isRightAnswer: false,
        text: 'China',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock8',
        isRightAnswer: false,
        text: 'United States',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
  const UiQuestion(
    'Mock9',
    text: 'What is the largest desert in the world?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock9',
        isRightAnswer: true,
        text: 'Sahara Desert',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock9',
        isRightAnswer: false,
        text: 'Gobi Desert',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock9',
        isRightAnswer: false,
        text: 'Arabian Desert',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock9',
        isRightAnswer: false,
        text: 'Antarctic Desert',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
  const UiQuestion(
    'Mock10',
    text: 'What is the largest waterfall in the world?',
    book: Books.gen,
    answers: [
      UiAnswer(
        qId: 'Mock10',
        isRightAnswer: true,
        text: 'Angel Falls',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock10',
        isRightAnswer: false,
        text: 'Niagara Falls',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock10',
        isRightAnswer: false,
        text: 'Victoria Falls',
        url: '',
        verse: '',
        verseReference: '',
      ),
      UiAnswer(
        qId: 'Mock10',
        isRightAnswer: false,
        text: 'Iguazu Falls',
        url: '',
        verse: '',
        verseReference: '',
      ),
    ],
  ),
];
